import { StyleSheet, Platform } from 'react-native';
import { Palette, fonts } from './theme';

export const createStyles = (palette: Palette, compactUI: boolean = false) => {
  const cardPadding = compactUI ? 6 : 8;
  const cardMargin = compactUI ? 8 : 12;
  const fontSize = {
    title: compactUI ? 13 : 14,
    subtitle: compactUI ? 9 : 10,
    body: compactUI ? 12 : 13,
  };

  return StyleSheet.create({
    activeCard: {
      borderColor: palette.accentStrong,
    },
    appFrame: {
      backgroundColor: palette.background,
      flex: 1,
      maxWidth: 500,
      overflow: 'hidden',
      width: '100%',
    },
    bottomBar: {
      alignItems: 'center',
      backgroundColor: palette.surface,
      borderTopColor: palette.border,
      borderTopWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: compactUI ? 10 : 14,
      paddingVertical: compactUI ? 6 : 8,
    },
    bottomControls: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      gap: 8,
      position: 'relative',
    },
    button: {
      alignItems: 'center',
      borderRadius: 4,
      flexGrow: 1,
      justifyContent: 'center',
      minWidth: 0,
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    buttonLabel: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontWeight: '700',
    },
    card: {
      backgroundColor: palette.surface,
      borderColor: palette.border,
      borderRadius: 4,
      borderStyle: 'dashed',
      borderWidth: 1,
      marginBottom: cardMargin,
      paddingBottom: cardPadding,
      paddingHorizontal: cardPadding,
      paddingTop: cardPadding + 2,
    },
    cardMain: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'space-between',
    },
    cardMenuButton: {
      alignItems: 'center',
      backgroundColor: palette.surface,
      borderColor: palette.border,
      borderRadius: 8,
      borderWidth: 1,
      height: compactUI ? 28 : 32,
      justifyContent: 'center',
      width: compactUI ? 28 : 32,
    },
    cardMenuButtonActive: {
      backgroundColor: palette.accentSoft,
      borderColor: palette.accentStrong,
    },
    cardMenuIcon: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: compactUI ? 14 : 16,
    },
    cardMenuItem: {
      paddingHorizontal: 12,
      paddingVertical: compactUI ? 8 : 10,
    },
    cardMenuItemActive: {
      backgroundColor: palette.accentSoft,
    },
    cardMenuLabel: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: fontSize.title,
    },
    cardMenuSheet: {
      backgroundColor: palette.surface,
      borderColor: palette.borderStrong,
      borderRadius: 10,
      borderWidth: 1,
      marginTop: 8,
      overflow: 'hidden',
    },
    cardSubtitle: {
      color: palette.textSecondary,
      fontFamily: fonts.regular,
      fontSize: fontSize.subtitle,
    },
    cardText: {
      flex: 1,
      gap: 2,
    },
    cardTitle: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: fontSize.title,
      fontWeight: '700',
    },
    checkbox: {
      alignItems: 'center',
      backgroundColor: palette.surface,
      borderColor: palette.border,
      borderRadius: 4,
      borderWidth: 2,
      height: 24,
      justifyContent: 'center',
      width: 24,
    },
    checkboxChecked: {
      backgroundColor: palette.accentStrong,
      borderColor: palette.accentStrong,
    },
    checkboxMark: {
      color: palette.surface,
      fontSize: 14,
      fontWeight: '700',
    },
    container: {
      backgroundColor: Platform.OS === 'web' ? '#000' : palette.background,
      flex: 1,
    },
    controlButton: {
      alignSelf: 'flex-end',
      borderRadius: 10,
      flexGrow: 0,
      height: compactUI ? 40 : 46,
      marginLeft: 12,
      paddingHorizontal: 0,
      paddingVertical: 0,
      width: compactUI ? 40 : 46,
    },
    controlIcon: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: compactUI ? 16 : 18,
    },
    destructiveButton: {
      backgroundColor: palette.destructiveSoft,
      borderColor: palette.destructiveStrong,
      borderStyle: 'dashed',
      borderWidth: 1,
    },
    destructiveLabel: {
      color: '#b02a3c',
    },
    disabledButton: {
      opacity: 0.5,
    },
    draggedOverCard: {
      borderTopColor: palette.accentStrong,
      borderTopWidth: 2,
      marginTop: 8,
    },
    draggingCard: {
      backgroundColor: palette.neutral,
      opacity: 0.5,
    },
    error: {
      color: '#b02a3c',
      fontFamily: fonts.medium,
      fontSize: 14,
      marginBottom: 4,
      paddingTop: 2,
    },
    heading: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: compactUI ? 18 : 21,
      fontWeight: '700',
    },
    headingBadge: {
      color: palette.textSecondary,
      fontFamily: fonts.medium,
      fontSize: compactUI ? 9 : 10,
      letterSpacing: 1,
      marginTop: 1,
      textTransform: 'uppercase',
    },
    infoBody: {
      color: palette.textSecondary,
      fontFamily: fonts.regular,
      fontSize: fontSize.body,
    },
    infoCard: {
      alignSelf: 'center',
      backgroundColor: palette.surface,
      borderColor: palette.borderStrong,
      borderRadius: 10,
      borderStyle: 'dashed',
      borderWidth: 1,
      gap: 10,
      maxWidth: 320,
      padding: 16,
    },
    infoMeta: {
      color: palette.textSecondary,
      fontFamily: fonts.medium,
      fontSize: 12,
    },
    inner: {
      flex: 1,
      paddingHorizontal: compactUI ? 8 : 12,
      paddingTop: compactUI ? 8 : 12,
    },
    input: {
      backgroundColor: palette.background,
      borderColor: palette.border,
      borderRadius: 4,
      borderWidth: 1,
      color: palette.textPrimary,
      fontFamily: fonts.regular,
      paddingHorizontal: 9,
      paddingVertical: 7,
    },
    linkHint: {
      color: palette.textSecondary,
      fontFamily: fonts.regular,
      fontSize: 12,
    },
    linkLabel: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: fontSize.body,
    },
    linkList: {
      gap: 8,
    },
    linkRow: {
      backgroundColor: palette.surface,
      borderColor: palette.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 2,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    linkRowActive: {
      backgroundColor: palette.accentSoft,
      borderColor: palette.accentStrong,
    },
    list: {
      paddingBottom: 92,
      paddingTop: 2,
    },
    menuBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: palette.overlay,
      zIndex: 10,
    },
    menuButton: {
      alignItems: 'center',
      backgroundColor: palette.surface,
      borderColor: palette.border,
      borderRadius: 6,
      borderWidth: 1,
      gap: 4,
      height: compactUI ? 30 : 34,
      justifyContent: 'center',
      paddingVertical: 6,
      width: compactUI ? 34 : 38,
    },
    menuContent: {
      gap: 12,
      paddingBottom: 4,
    },
    menuDivider: {
      borderBottomWidth: 1,
      borderColor: palette.border,
      borderStyle: 'dashed',
      marginVertical: 4,
      opacity: 0.7,
    },
    menuHeader: {
      gap: 2,
      paddingBottom: 4,
    },
    menuHeaderEmail: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: fontSize.body,
      marginBottom: 4,
    },
    menuHeaderLabel: {
      color: palette.textSecondary,
      fontFamily: fonts.medium,
      fontSize: fontSize.subtitle,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    menuIconLine: {
      backgroundColor: palette.textPrimary,
      borderRadius: 1,
      height: 2,
      width: compactUI ? 14 : 16,
    },
    menuItem: {
      borderRadius: 6,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    menuItemActive: {
      backgroundColor: palette.accentSoft,
    },
    menuItemDestructive: {
      backgroundColor: palette.destructiveSoft,
      borderColor: palette.destructiveStrong,
      borderStyle: 'dashed',
      borderWidth: 1,
      marginTop: 4,
    },
    menuItemDestructiveActive: {
      backgroundColor: palette.destructiveStrong,
    },
    menuItemHint: {
      color: palette.textSecondary,
      fontFamily: fonts.medium,
      fontSize: 12,
    },
    menuItemLabel: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: fontSize.title,
    },
    menuItemPrimary: {
      backgroundColor: palette.accentSoft,
      borderColor: palette.accentStrong,
      borderStyle: 'dashed',
      borderWidth: 1,
      marginTop: 4,
    },
    menuItemPrimaryActive: {
      backgroundColor: palette.accentStrong,
    },
    menuItemRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
    },
    menuPanel: {
      backgroundColor: palette.surface,
      borderColor: palette.borderStrong,
      borderRadius: 10,
      borderStyle: 'dashed',
      borderWidth: 1,
      elevation: 6,
      gap: 12,
      maxHeight: '75%',
      padding: 12,
      position: 'absolute',
      right: 14,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      top: 54,
      width: 210,
      zIndex: 11,
    },
    menuSection: {
      gap: 6,
    },
    menuSectionLabel: {
      color: palette.textSecondary,
      fontFamily: fonts.medium,
      fontSize: 11,
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    menuSpacer: {
      flex: 1,
      minHeight: 10,
    },
    menuThemeButton: {
      backgroundColor: palette.surface,
      borderColor: palette.border,
      borderRadius: 4,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    menuThemeButtonActive: {
      backgroundColor: palette.accentSoft,
      borderColor: palette.accentStrong,
    },
    menuThemeButtonHover: {
      backgroundColor: palette.accentSoft,
      borderColor: palette.accentStrong,
    },
    menuThemeButtonLabel: {
      color: palette.textSecondary,
      fontFamily: fonts.medium,
      fontSize: 12,
    },
    menuThemeButtonLabelActive: {
      color: palette.textPrimary,
    },
    menuThemeOptions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    modalActions: {
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'flex-end',
    },
    modalBackdrop: {
      alignItems: 'center',
      backgroundColor: palette.overlay,
      flex: 1,
      justifyContent: 'center',
      padding: 16,
    },
    modalCard: {
      backgroundColor: palette.surface,
      borderColor: palette.borderStrong,
      borderRadius: 6,
      borderStyle: 'dashed',
      borderWidth: 1,
      gap: 6,
      maxWidth: 420,
      minWidth: 300,
      padding: 12,
      width: '90%',
    },
    modalTitle: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: 17,
      fontWeight: '700',
    },
    nowPlayingInfo: {
      flex: 1,
      paddingRight: 12,
    },
    nowPlayingSubtitle: {
      color: palette.textSecondary,
      fontFamily: fonts.regular,
      fontSize: 12,
    },
    nowPlayingTitle: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: fontSize.title,
      fontWeight: '700',
    },
    playingCard: {
      backgroundColor: palette.accentSoft,
    },
    primaryButton: {
      backgroundColor: palette.accentSoft,
      borderColor: palette.accentStrong,
      borderStyle: 'dashed',
      borderWidth: 1,
    },
    primaryLabel: {
      color: palette.textPrimary,
    },
    searchBar: {
      backgroundColor: palette.surface,
      borderBottomWidth: 1,
      borderColor: palette.border,
      flexDirection: 'row',
      gap: 8,
      padding: compactUI ? 8 : 10,
    },
    searchButton: {
      width: compactUI ? 34 : 38,
    },
    searchCloseButton: {
      alignItems: 'center',
      backgroundColor: palette.neutral,
      borderColor: palette.border,
      borderRadius: 4,
      borderWidth: 1,
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    searchCloseLabel: {
      color: palette.textPrimary,
      fontFamily: fonts.medium,
      fontSize: 12,
    },
    searchIcon: {
      color: palette.textPrimary,
      fontFamily: fonts.bold,
      fontSize: compactUI ? 14 : 16,
    },
    searchInput: {
      backgroundColor: palette.background,
      borderColor: palette.border,
      borderRadius: 4,
      borderWidth: 1,
      color: palette.textPrimary,
      flex: 1,
      fontFamily: fonts.regular,
      fontSize: fontSize.title,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    secondaryButton: {
      backgroundColor: palette.neutral,
      borderColor: palette.border,
      borderStyle: 'dashed',
      borderWidth: 1,
    },
    settingsLabel: {
      color: palette.textPrimary,
      fontFamily: fonts.medium,
      fontSize: fontSize.title,
    },
    settingsRow: {
      alignItems: 'center',
      borderBottomColor: palette.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 12,
    },
    settingsSwitch: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    subhead: {
      color: palette.textSecondary,
      fontFamily: fonts.regular,
      fontSize: fontSize.body,
      paddingBottom: 4,
    },
    submenu: {
      backgroundColor: palette.background,
      borderColor: palette.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 8,
      padding: 10,
    },
    themeOption: {
      borderColor: palette.border,
      borderRightWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    themeOptionActive: {
      backgroundColor: palette.accentSoft,
    },
    themeOptionLabel: {
      color: palette.textSecondary,
      fontFamily: fonts.medium,
      fontSize: 11,
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    themeOptionLabelActive: {
      color: palette.textPrimary,
    },
    themeOptionLast: {
      borderRightWidth: 0,
    },
    themeSwitch: {
      alignSelf: 'flex-start',
      backgroundColor: palette.surface,
      borderColor: palette.border,
      borderRadius: 6,
      borderWidth: 1,
      flexDirection: 'row',
      marginBottom: 8,
      overflow: 'hidden',
    },
    topBar: {
      alignItems: 'center',
      backgroundColor: palette.surface,
      borderBottomColor: palette.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingBottom: compactUI ? 6 : 8,
      paddingHorizontal: compactUI ? 10 : 14,
      paddingTop: 6,
    },
    topBarActions: {
      flexDirection: 'row',
      gap: 8,
    },
    volumeButton: {
      alignItems: 'center',
      borderRadius: 10,
      flexGrow: 0,
      height: compactUI ? 40 : 46,
      justifyContent: 'center',
      width: compactUI ? 40 : 46,
    },
    volumeFillVertical: {
      backgroundColor: palette.accentStrong,
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
    },
    volumeIcon: {
      fontSize: compactUI ? 18 : 20,
    },
    volumePopover: {
      alignItems: 'center',
      backgroundColor: palette.surface,
      borderColor: palette.borderStrong,
      borderRadius: 12,
      borderStyle: 'dashed',
      borderWidth: 1,
      bottom: compactUI ? 55 : 61,
      position: 'absolute',
      right: compactUI ? 59 : 65,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
    },
    volumeThumb: {
      backgroundColor: palette.surface,
      borderColor: palette.borderStrong,
      borderRadius: 8,
      borderWidth: 2,
      height: 16,
      left: -4,
      position: 'absolute',
      right: -4,
      transform: [{ translateY: 8 }],
    },
    volumeTrackVertical: {
      backgroundColor: palette.background,
      borderColor: palette.border,
      borderRadius: 12,
      borderWidth: 1,
      height: 160,
      overflow: 'hidden',
      position: 'relative',
      width: 46,
    },
    volumeValueLabel: {
      color: palette.textSecondary,
      fontFamily: fonts.bold,
      fontSize: 14,
    },
    webWrapper: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
      width: '100%',
    },
  });
};
export type AppStyles = ReturnType<typeof createStyles>;
